version: '3.7'
services:

  upyco2-service:
    image: gcr.io/core-iot-sensors/upyco2-esp32:1.0.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - esp32net

networks:
  esp32net:
    driver: bridge
    name: esp32_network
