version: '3.7'
services:

  upyco2-service:
    image: gcr.io/core-iot-sensors/upyco2-esp32:1.0.0
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - esp32net

  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/etc/nginx/cache
      - ./nginx/ssl:/etc/nginx/ssl
      #- /etc/letsencrypt/live/apis.lemariva.com-0001:/etc/nginx/ssl
      - ./nginx/ssl/bot:/etc/nginx/ssl/bot
    networks:
      - esp32net

networks:
  esp32net:
    driver: bridge
    name: esp32_network
